version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    environment:
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}
      - DB_POOL_RECYCLE=${DB_POOL_RECYCLE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPIRE_TIME=${REDIS_EXPIRE_TIME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_ID=${RABBITMQ_ID}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - postgres
      - redis
    ports:
      - "5050:5050"
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  redis:
    image: redis:latest
    command: redis-server --requirepass redis!123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_task.worker.celery_app worker --loglevel=info
    environment:
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}
      - DB_POOL_RECYCLE=${DB_POOL_RECYCLE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPIRE_TIME=${REDIS_EXPIRE_TIME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_ID=${RABBITMQ_ID}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - web
      - postgres
      - redis

  celery_beat:
    build: .
    command: celery -A app.celery_task.worker.celery_app beat --loglevel=info
    environment:
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}
      - DB_POOL_RECYCLE=${DB_POOL_RECYCLE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPIRE_TIME=${REDIS_EXPIRE_TIME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_ID=${RABBITMQ_ID}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - web
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
